// AUTO-GENERATED by build.rs — do not edit by hand.
// To add a module: create src/modules/my_name/mod.rs + add `pub mod my_name;` to modules/mod.rs.

use crate::modules::CadModule;

/// Returns one boxed instance of every registered CAD module.
/// Called once at startup by `Ribbon::new()`.
pub fn all_modules() -> Vec<Box<dyn CadModule>> {
	vec![
		Box::new(super::home::HomeModule),
		Box::new(super::model::ModelModule),
		Box::new(super::insert::InsertModule),
		Box::new(super::annotate::AnnotateModule),
		Box::new(super::view::ViewModule),
		Box::new(super::manage::ManageModule),
		Box::new(super::layout::LayoutModule),
	]
}
